version: "3"

services:
  supplier-platform:
    container_name: supplier-platform
    tty: true
    build: ./supplier-platform
    ports:
      - "8084:8084"
      - "4084:4084"
    volumes:
      - ../build/libs:/vol/development/

  rendering-service:
    build: ./rendering-service
    container_name: "rendering-service"
    ports:
      - "5000:5000"
    volumes:
      - ../build/express:/usr/rendering-service/